// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/sethvargo/go-envconfig"
	"starter-kit/server"
	"starter-kit/server/config"
	"starter-kit/server/handler"
)

// Injectors from wire.go:

// InitializeHTTPServer ...
func InitializeHTTPServer(l envconfig.Lookuper) (*server.HTTPServer, error) {
	httpServerConfig := config.NewHTTPServerConfig(l)
	healthcheckHandler := handler.NewHealthCheckHandler(httpServerConfig)
	httpServerConfigHandler := handler.NewHTTPServerConfigHandler(httpServerConfig)
	httpServer := server.NewHTTPServer(httpServerConfig, healthcheckHandler, httpServerConfigHandler)
	return httpServer, nil
}
