// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/spals/starter-kit/grpc/proto"
	"github.com/spals/starter-kit/grpc/server/impl"
)

// Injectors from wire.go:

// InitializeGrpcServer ...
func InitializeGrpcServer(config *proto.GrpcServerConfig) (*GrpcServer, error) {
	configServer := impl.NewConfigServer(config)
	healthServer := impl.NewHealthServer(config)
	grpcServer := NewGrpcServer(config, configServer, healthServer)
	return grpcServer, nil
}
