// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/sethvargo/go-envconfig"
	"github.com/spals/starter-kit/grpc/server/config"
	"github.com/spals/starter-kit/grpc/server/impl"
)

// Injectors from wire.go:

// InitializeGrpcServer ...
func InitializeGrpcServer(l envconfig.Lookuper) (*GrpcServer, error) {
	grpcServerConfig := config.NewGrpcServerConfig(l)
	healthRegistry := impl.NewHealthRegistry()
	configServer := impl.NewConfigServer(grpcServerConfig, healthRegistry)
	grpcServer := NewGrpcServer(grpcServerConfig, healthRegistry, configServer)
	return grpcServer, nil
}
