// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/sethvargo/go-envconfig"
	"github.com/spals/starter-kit/http/server/config"
	"github.com/spals/starter-kit/http/server/handler"
)

// Injectors from wire.go:

// InitializeHTTPServer ...
func InitializeHTTPServer(l envconfig.Lookuper) (*HTTPServer, error) {
	httpServerConfig := config.NewHTTPServerConfig(l)
	healthcheckHandler := handler.NewHealthCheckHandler(httpServerConfig)
	httpServerConfigHandler := handler.NewHTTPServerConfigHandler(httpServerConfig)
	httpServer := NewHTTPServer(httpServerConfig, healthcheckHandler, httpServerConfigHandler)
	return httpServer, nil
}
