name: Golang Lint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  golangci-lint:
    strategy:
        matrix:
          go-version: [1.15.x]
#          go-version: [1.15.x, 1.16.x]
          os: [macos-latest]
#          NOTE: If enabling Linux or Windows builds, also enable Linux/Windows build cache below
#          os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env: 
      GO111MODULE: on

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Build Cache
      uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Mac)
        # * Build cache (Linux)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/Library/Caches/go-build
#          ~/.cache/go-build
#          %LocalAppData%\go-build
        key: ${{ runner.os }}-golint-${{ matrix.go-version }}-${{ hashFiles('**/http/go.sum') }}-${{ hashFiles('**/grpc/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golint-${{ matrix.go-version }}-

    - name: Lint Http
      uses: golangci/golangci-lint-action@v2
      with:
        skip-build-cache: true
        skip-go-installation: true
        skip-pkg-cache: true
        version: latest
        working-directory: http

    - name: Lint Grpc
      uses: golangci/golangci-lint-action@v2
      with:
        skip-build-cache: true
        skip-go-installation: true
        skip-pkg-cache: true
        version: latest
        working-directory: grpc
