name: HTTP DockerHub CD

on:
  workflow_run:
    workflows: [ "HTTP Tests CI" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  publish-docker-http:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Docker Labels and Tags
      id: docker-meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: spals/starter-kit-http
        labels: |
          org.opencontainers.image.title=starter-kit-http
          org.opencontainers.image.description=Starting boilerplate for Golang HTTP servers
          org.opencontainers.image.vendor=Spals
        tags: |
          type=edge,branch=main
          type=ref,event=branch
          type=ref,event=pr
          type=schedule
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    # See https://github.com/marketplace/actions/docker-login#docker-hub
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Docker Cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-http-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-http-buildx-

    - name: Publish Docker Image
      uses: docker/build-push-action@v2
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        context: ./http
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move Docker Cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
