name: HTTP Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-http:
    runs-on: ubuntu-latest
    env: 
      GO111MODULE: on
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: cd ${{ github.workspace }}/http && go build -v ./...

    - name: Test
      run: cd ${{ github.workspace }}/http && go test -v ./...
