name: HTTP Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./http

jobs:
  build-http:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [macos-latest, ubuntu-latest]
#        NOTE: If enabling Windows builds, also enable Windows build cache below
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env: 
      GO111MODULE: on

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Build Cache
      uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Mac)
        # * Build cache (Linux)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/Library/Caches/go-build
          ~/.cache/go-build
#          %LocalAppData%\go-build
        key: ${{ runner.os }}-gotest-${{ matrix.go-version }}-${{ hashFiles('**/http/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gotest-${{ matrix.go-version }}-

    - name: Run Build
      run: go build -v ./...

    - name: Run Tests
      run: go test ./...
